before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Vpwcb3vVdMdtDbtsFGd7ykUdSCfna3u/JAAq7DG7mi415Aqq3HXhbL16MIQDRPa5RUuziMVuQ8//guQ2D31+O8LusIAn577SdZ8NS04bib06qq12nlEJKVfm0I4naCYW5+aB1n1TPZjI+lRiV92LvWVC5seQHQRtwzzuctSNlzJsLim1Aq0nACu2R6KBCGRxLYg+dt/BZ1sMSKNXFOMhXAo2CTwKJEySqIhUehtzpgLVSGpVaAf622BWohr6ZCISvy3pMtB6NI+EMtWXBaieiZHhOlSYjNS5Ok/IgS54N42Fju2Jc9pW2SocToddu5ha4K2AnZulKswC0t0TTBaajPqhVkEZ9lGmCMBHbUPelB0p6hhQKzpQXvUIhz2xm+77BrRA69YQCayZdZ/8rDNP65OyMVPfoQJXhMzWAdbXZRlrkToTUj3lLnd8/5HrYvBCL7glMfdg60hZoiZL6Uz9Ja47RCcF7IQLOpl88HMoCxzSOS3wwvr68xzLrNktbAeNe3vmye7cYJrTf1foewUm1w8OImuC1UlE/ibD199wd0jaZIT79pjsAgwczRT0fXUyYwrALDjoAWzi0hlKw5XYHEllcXsMdkZwPhv7OTDCGdqO450xkwBVgT1s8qxxUgRiAy3YYqKlhIVuYohga4C8nhsCERc//HlMEz26H6A54Bs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
